---
  - hosts: worker:ingress:storage
    any_errors_fatal: true
    name: "Validate Nodes are Ready"
    become: yes
    run_once: true

    roles:
      - node-smoke-test

  - hosts: master
    any_errors_fatal: true
    name: Smoke Test Master Node
    become: yes
    serial: 1
    vars_files:
      - group_vars/all.yaml

    roles:
      - smoketest
