---
  - include: _all.yaml
  - include: _additional-files.yaml
  - include: _certs.yaml
  - include: _kubeconfig.yaml
  - include: _packages-repo.yaml
    when: allow_package_installation|bool == true
  # docker
  - include: _docker.yaml
    when: docker.enabled|bool == true
  # kubernetes
  - include: _kubelet.yaml
  - include: _kube-apiserver.yaml
  - include: _kube-scheduler.yaml
  - include: _kube-controller-manager.yaml
  # validating has a dependecy on the API server for the static pods
  - include: _validate-control-plane-node.yaml
  - include: _kube-proxy.yaml
  - include: _label-nodes.yaml
  - include: _calico.yaml
    when: cni.enabled|bool == true and cni.provider == "calico"
  - include: _calico-validate.yaml
    when: cni.enabled|bool == true and cni.provider == "calico"
  - include: _weave.yaml
    when: cni.enabled|bool == true and cni.provider == "weave"
  - include: _weave-validate.yaml
    when: cni.enabled|bool == true and cni.provider == "weave"
  - include: _contiv.yaml
    when: cni.enabled|bool == true and cni.provider == "contiv"
  - include: _nginx-ingress.yaml
    when: configure_ingress|bool == true
  - include: _storage.yaml
    when: configure_storage|bool == true
  - include: _update-version.yaml